### ISSUE TITLE
Book Dash 2024: November at TU Delft

### ISSUE THREAD

**Issue by EstherPlomp** [the-turing-way/bookdash#17]
Drafting up tasks and information for the November in-person hub at Delft

## People who need to be involved/updated: 
- Lena
- @c-martinez 
- Tanya

## Dates & timeline
- 5-6 November

Tuesday 5 November

- 10:00 - Introduction & Getting to know each other / checking how to work together
- 12:00 - Lunch provided by university catering
- 13:00 - Working session
- 14:30 - Break
- 17:30 - Wrap up and setting goals for the next day
- 18:00 - Dinner at Faculty Club

Wednesday 6 November

- 09:00 - Start
- 10:30 - Shared break
- 12:00 - Lunch provided by university catering
- 13:00 - 15:00 - Working session
- 15:00 - 15:30 Wrap up & short share out
- 15:30 - Drinks/social at event location

## Task for an in-person Event - Local HUBS

- [ ] Book location for in-person events
- [ ] Collate participants’ preference for travel, meal, accommodation, and accessibility request through the registration form
- [ ] Send an email to the participants regarding their travel, accommodation, schedule, and meal
- [ ] Book catering for lunch and coffee breaks
- [ ] Double-check with each participant if their plan as given on their registration hasn’t changed

**Comment by c-martinez** [comment]
Is it an idea to also reach out to people in:
- The NL-RSE network
- eScience Fellows
- DCC's

**Comment by EstherPlomp** [comment]
Absolutely! Added it to the list of people to contact, thanks @c-martinez!
